### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by ScottishRoss** [Dani3lSun/docker-db-apex-dev#23]
I get this error when trying to build the docker image.

Error processing tar file(exit status 1): write /files/LINUX.X64_180000_db_home.zip: no space left on device

I have over 300GB of space left on that drive, and I'm not sure what else it could be. I have cleared all previous images and containers of failed Docker builds too.

**Comment by Dani3lSun** [comment]
Hey @ScottishRoss 
unfortunately Docker has an own virtual disc on Mac or Windows based OS, because Docker only runs native of Linux. This means that a small VM layer is required on all other OS. On Mac for example you can configure the size of this virtual disc, and my guess is, that this disc is out of space in you environment:
<img width="504" alt="Screen Shot 2019-05-20 at 09 50 55" src="https://user-images.githubusercontent.com/698942/58005079-22b69000-7ae5-11e9-8355-945b9915a1b5.png">

**Comment by ScottishRoss** [comment]
Thanks for the advice. Looking into how to change the default vm created by Docker seems to have fixed it. 
Source: https://github.com/crops/docker-win-mac-docs/wiki/Windows-Instructions-(Docker-Toolbox)
