### ISSUE TITLE
Docker-compose APEX

### ISSUE THREAD

**Issue by JustAPhrog** [Dani3lSun/docker-db-apex-dev#32]
Do you plan to create `docker-compose.yml` for APEX?

**Comment by Dani3lSun** [comment]
No I‘m not really planning it...
This image build scripts are not very „dockerish“, which means that all software for running APEX (e.g. DB, Tomcat, ORDS, etc.) is installed in 1 container, if you start the container you should have everything in place...
So this is more like a small VM rather than the traditional docker container (1 software per container) :) Therefore I don‘t see any needs for a docker-compose file.
