### ISSUE TITLE
Prebuild image

### ISSUE THREAD

**Issue by mojtabye** [Dani3lSun/docker-db-apex-dev#8]
why there is not any prebuild image?
building image just taking time :(

**Comment by Dani3lSun** [comment]
Hey @mojtabye 
that is simple, because Oracle licensing doesn´t allow that...
If you download Oracle Software from oracle.com you first have to accept the license agreement of them.
If I would build an Docker image with Oracle software and upload it to Docker Hub it will voilate the licensing...
<img width="853" alt="oracle_database_software_downloads___oracle_technology_network___oracle" src="https://user-images.githubusercontent.com/698942/34791588-adc7a93e-f645-11e7-95b4-80bd63e9c659.png">
